name: Run Attempt
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello World"
          echo ${{ github.workspace }}
          echo ${{ github.run_attempt }}
          echo ${{ github.actor }}
